config/routes.rb
Rails.application.routes.draw do
devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'user_registrations'}

resources :users
resources :orders, only: [:index, :show, :create, :destroy]
resources :products do
  resources :comments
end

mount ActionCable.server => '/cable'

get 'static_pages/index'
get 'static_pages/about'
get 'static_pages/contact'
get 'static_pages/landing_page'
get 'static_pages/thank_you'

post 'static_pages/thank_you'
post 'payments/create'

root 'static_pages#landing_page'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
    @products = Product.limit(3)
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver_now
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="page-wrap">

  <h1>About</h1>
  <p>
    Bike Imperium is the place to buy bikes, bike components, and cycling accessories. If you’re looking for a new or used bike, you’ve come to the right place. The choice is enormous and prices are great.
  </p>

</div>

app/views/static_pages/contact.html.erb
<div class="page-wrap">

  <h1>Contact us</h1>

  <%= flash[:notice] %>

  <%= form_tag("/static_pages/thank_you") do %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-12">
        <div class="form-group">
          <%= label_tag :name %>
          <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name", required: "true"%>
        </div> <!-- end form-group -->
        <div class="form-group">
          <%= label_tag :email, "Email Address" %>
          <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email", required: "true", type: "email" %>
        </div> <!-- end form-group -->
        <div class="form-group">
          <%= label_tag :message %>
          <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message", required: "true" %>
        </div> <!-- end form-group -->
        <%= submit_tag "Send", class: "btn btn-info" %>
      </div> <!-- end col -->
    </div> <!-- end row -->

  <% end %>

</div> <!-- end page-wrap -->

app/views/static_pages/index.html.erb
<div class="page-wrap">

  <h1 class="bike-logo">Welcome to<br><span class="header-logo">Bike Imperium</span><br><%= image_tag("icon.png", width: '50%')%></h1>

  <h2 id="image-header">Your source for used bikes in Munich</h2>
  <div class="index-image">
    <%= image_tag("bike.jpg", title: 'Rails Application', class: 'intro-image') %>
  </div> <!-- end index-image -->

</div> <!-- end page-wrap -->

app/views/static_pages/landing_page.html.erb
<!-- carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @products.each_with_index do |product, index| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= " active" if index == 0 %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url, class: "carousel-image") %>
      <div class= "carousel-caption">
        <%= product.name %>
      </div> <!-- end carousel-caption -->
    </div> <!-- end item -->
    <% end %>
  </div> <!-- end carousel-inner -->

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> <!-- end carousel -->

app/views/static_pages/thank_you.html.erb
<div class="page-wrap row">
  <br>
  <div class="col-md-6 col-md-offset-1 col-sm-12">
    <div class="panel panel-default panel-thankyou">
      <div class="panel-body">
        <p>Thank you. We have received your message and will respond as soon as possible.</p>
      </div> <!-- end panel-body -->
    </div> <!-- end panel -->
    <%= link_to 'Back', static_pages_landing_page_path, class:"btn btn-default" %>
  </div> <!-- end col -->
</div> <!-- end row -->