config/routes.rb
Rails.application.routes.draw do
devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'user_registrations'}

resources :users
resources :orders, only: [:index, :show, :create, :destroy]
resources :products do
  resources :comments
end

mount ActionCable.server => '/cable'

get 'static_pages/index'
get 'static_pages/about'
get 'static_pages/contact'
get 'static_pages/landing_page'
get 'static_pages/thank_you'

post 'static_pages/thank_you'
post 'payments/create'

root 'static_pages#landing_page'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bike Imperium</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Raleway|Eater+Caps" rel="stylesheet">
  <!-- icon for title -->
  <%= favicon_link_tag 'icon.ico' %>
  <!-- icon for nav bar -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><i class="fa fa-bicycle" style="font-size: 25px"></i><%= link_to 'Bike Imperium', root_path, { :class=>"bike-imperium-logo" } %></a>
      </div> <!-- end navbar-header -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', static_pages_index_path %></li>
        <li><%= link_to 'About', static_pages_about_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to "Contact", static_pages_contact_url %></li>

        <!-- Sign up Log in -->
        <div class="navbar-form navbar-right">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"login") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class:"login") %>
        <% end %>
        </div> <!-- end navbar-form navbar-right -->

        <!-- search box -->
        <%= form_tag(products_path, method: "get", class:"navbar-form navbar-right") do %>
          <%= text_field_tag(:q, "", type: "text", class: "form-control", placeholder: "search text") %>
          <%= submit_tag("Search", class: "btn btn-default") %>
        <% end %>
      </ul>
    </div> <!-- end container-fluid -->
  </nav>

  <!-- Flash Notice Tags -->
  <br>
  <% if notice %>
    <p id="notice" class="alert alert-warning">
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-danger">
      <%= alert %>
    </p>
  <% end %>
  <br><br>



  <%= yield %>

  <footer>
    &copy; 2017 Bike Imperium
  </footer>

</body>
</html>